#!/usr/bin/with-contenv bash


log() {
    echo "[mod-freezetag] $1"
}

# Check if DOCKER_MODS_DEBUG is set and true
if [[ "${DOCKER_MODS_DEBUG}" == "true" ]]; then
    echo "[mod-freezetag] (DEBUG) Starting svc-qbittorrent-freezetag..."
fi



# Check if the CATEGORY_DIR and FROZEN_DIR environment variables are set and that the directories exist
if [[ -z "${CATEGORY_DIR}" ]]; then
    log "Error: The CATEGORY_DIR environment variables must be set."
    exit 1
fi

if [[ -z "${FROZEN_DIR}" ]]; then
    log "Error: The FROZEN_DIR environment variables must be set."
    exit 1
fi

if [[ ! -d "${CATEGORY_DIR}" ]]; then
    log "Error: The CATEGORY_DIR (${CATEGORY_DIR}) does not exist."
    exit 1
fi

if [[ ! -d "${FROZEN_DIR}" ]]; then
    log "Error: The FROZEN_DIR (${FROZEN_DIR}) does not exist."
    exit 1
fi

# Check if the FROZEN_DIR is empty
if [ ! -z "$(find ${FROZEN_DIR} -mindepth 1 -print -quit)" ]; then
    log "Error: The FROZEN_DIR (${FROZEN_DIR}) is not empty."
    exit 1
fi

spaces='                                                            '
CAT_display="${FREEZE_CATEGORY}${spaces}"
CAT_DIR_display="${CATEGORY_DIR}${spaces}"
FRO_DIR_display="${FROZEN_DIR}${spaces}"
CAT_UMASK_display="${CATEGORY_UMASK}${spaces}"
echo "\
+---------------------------------------------------------+
|                     Freezetag mod loaded                |
+---------------------------------------------------------+
|  Freeze  category    : ${CAT_display::33}|
|  Category directory  : ${CAT_DIR_display::33}|
|  Frozen directory    : ${FRO_DIR_display::33}|
|  Category UMASK      : ${CAT_UMASK_display::33}|
+---------------------------------------------------------+
"

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "mountpoint -q ${FROZEN_DIR}" \
        freezetag mount \
        --uid "${PUID}" \
        --gid "${PGID}" \
        "${CATEGORY_DIR}" \
        "${FROZEN_DIR}"