#!/usr/bin/with-contenv bash

# Check if DOCKER_MODS_DEBUG is set and true
if [[ "${DOCKER_MODS_DEBUG}" == "true" ]]; then
    LOGFILE="/tmp/freezetag.log"

    log() {
        echo "$(date '+%m/%d/%y %H:%M:%S') [Freezetag] - $1" >> $LOGFILE
    }

    # Initial logging
    log "Starting svc-qbittorrent-freezetag..."
else
    log() {
        # No-op function to avoid logging when DOCKER_MODS_DEBUG is not true
        :
    }
fi

# Log the execution timestamp
log "Service script started."


# Check if the CATEGORY_DIR and FROZEN_DIR environment variables are set and that the directories exist
if [[ -z "${CATEGORY_DIR}" || -z "${FROZEN_DIR}" ]]; then
    log "Error: The CATEGORY_DIR and FROZEN_DIR environment variables must be set."
    exit 1
fi

if [[ ! -d "${CATEGORY_DIR}" ]]; then
    log "Error: The CATEGORY_DIR was set to ${CATEGORY_DIR}, but the directory does not exist."
    exit 1
fi

if [[ ! -d "${FROZEN_DIR}" ]]; then
    log "Error: The FROZEN_DIR was set to ${FROZEN_DIR}, but the directory does not exist."
    exit 1
fi

# Execute the main command
exec \
    freezetag mount \
    --uid "${PUID}" \
    --gid "${PGID}" \
    "${CATEGORY_DIR}" \
    "${FROZEN_DIR}" &

while ! mount | grep -q "${FROZEN_DIR}"; do
    echo "Waiting for mount to be available..."
    sleep 1
done

exec s6-notifywhenup -- echo "Mount is ready, service is now up."
log "Mount successful."