#!/usr/bin/with-contenv bash

Alpine
echo "\
    # fuse \
    # py3-pip \
    git" >> /mod-repo-packages-to-install.list

echo "\
    git+https://github.com/undaunt/freezetag" >> /mod-pip-packages-to-install.list
