#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# This script monitors qBittorrent for removed torrents and deletes orphan .ftag files
# Adapted from https://github.com/t-anc/GSP-Qbittorent-Gluetun-sync-port-mod/blob/main/root/etc/s6-overlay/s6-rc.d/svc-mod-gluetun-sync-port/run

# Configuration Variables
MAX_SLEEP_TIME="${FTAG_SLEEP:-15}"   # Maximum sleep interval
RETRY_DELAY="${FTAG_RETRY_DELAY:-10}"  # Retry delay on errors
INIT_RETRY_WAIT="${FTAG_INIT_RETRY_WAIT:-10}"  # Initial retry wait time
DEBUG="${DOCKER_MODS_DEBUG:-false}"

QBITTORRENT="${FTAG_QBT_ADDR:-http://localhost:${WEBUI_PORT:-8080}}"
[ -n "${FTAG_QBT_PASSWORD_FILE}" ] && FTAG_QBT_PASSWORD="$(cat "${FTAG_QBT_PASSWORD_FILE}")"
QBT_USERNAME="${FTAG_QBT_USERNAME}"
QBT_PASSWORD="${FTAG_QBT_PASSWORD}"
QBT_COOKIES="--cookie-jar /tmp/cookies.txt --cookie /tmp/cookies.txt"
[ "${FTAG_CERT_CHECK,,}" = 'false' ] && CURL_OPT='--insecure'
CONF_FILE='/config/qBittorrent/qBittorrent.conf'
CATEG_FILE="/config/qBittorrent/categories.json"
CATEGORY_DL="${FTAG_DL_CATEGORY:-}"
CATEGORY_FZ="${FTAG_FZ_CATEGORY:-${CATEGORY_DL}_frozen}"

# Get Category path
CATEGORY_DL_DIR=$(jq -r --arg category "$CATEGORY_DL" '.[$category].save_path' "$CATEG_FILE")

RESPONSE_FILE="/config/qbittorrent_rid"  # Store the last response ID, persistant storage

# Functions
log() {
    echo "[mod-freezetag] INFO: ${1}" >&2
}
log_warning() {
    echo "[mod-freezetag] WARNING: ${1}" >&2
}
log_error() {
    echo "[mod-freezetag] ERROR: ${1}" >&2
}
log_debug() {
    if [ "${DEBUG,,}" = 'true' ]; then
        echo "[mod-freezetag] DEBUG: ${1}" >&2
    fi
}


qbt_login() {
    curl --fail --silent \
        ${CURL_OPT} \
        ${QBT_COOKIES} \
        --url "${QBITTORRENT}/api/v2/auth/login" \
        --data "username=${QBT_USERNAME}" \
        --data "password=${QBT_PASSWORD}"
}

init_checks(){
  # Enable or not init_checks
  if [ "${FTAG_SKIP_INIT_CHECKS,,}" = 'true' ]; then
    return 0
  fi

  # Check 1 : 
  #   In case of HTTPS, check if qBittorrent is using a trusted certificate.

  if echo "${QBITTORRENT}" | grep -iq 'https://' ;then
    curl ${CURL_OPT} --silent --output /dev/null "${QBITTORRENT}"
    if [ "$?" -eq '60' ]; then
      err='true'
      log_warning "Your qBittorrent certificate is untrusted. See HTTPS section in https://github.com/t-anc/GSP-Qbittorent-Gluetun-sync-port-mod#troubleshooting."
    fi
  fi

  # Check 2 : 
  #   Check for the auth bypass in qbittorrent's config file,
  #   or check for bad credentials.

  if [ ! -f "${CONF_FILE}" ]; then
    log_warning "${CONF_FILE} not found, can't check the The \"Bypass authentication for clients on localhost\" setting. Running in standalone mode."
  else
    if { [ -z "${QBT_USERNAME}" ] || [ -z "${QBT_PASSWORD}" ] ;} && [ "$(grep 'LocalHostAuth' ${CONF_FILE} | awk -F'=' '{print $2}')" != "false" ]; then
      err='true'
      log_error "The \"Bypass authentication for clients on localhost\" setting is not set."
    elif [ -n "${QBT_USERNAME}" ] && [ -n "${QBT_PASSWORD}" ] && [ "$(qbt_login)" != "Ok." ]; then
      err='true'
      log_error "Qbittorrent authentication failed, check the credentials."
    fi
  fi

  # Check 3 :
  #   Check for "Host header validation".
  if [ "$(curl ${CURL_OPT} --write-out '%{http_code}' --silent --output /dev/null "${QBITTORRENT}")" -eq 401 ]; then
    err='true'
    log_error "Qbittorrent returned 401. Is the \"Enable Host header validation\" setting set ? Is $(basename "${QBITTORRENT%:*}") whitelisted ?"
  fi


  # Display Check results.
  # In case of failed checks, enter an empty loop : 
  #   -> exiting the script would make s6-overlay to re-run it.
  if [ -n "${err}" ];then
    log_error "Init checks failed, exiting the mod. You can disable init checks by setting \"FTAG_SKIP_INIT_CHECKS=true\"."
    while :; do
      sleep 3600
    done
  else
    log "Init checks passed."
  fi
}

update_combined_data() {
    local full_list=$1
    local rid=$2

    # Construct the JSON structure
    local combined=$(jq -n --argjson torrents "$full_list" --arg rid "$rid" \
        '{rid:($rid | tonumber),torrents:$torrents}')
    
    # Save the combined structure to a file
    echo "$combined" > "$RESPONSE_FILE"
    
    # Return the combined JSON
    echo "$combined"
}

fetch_full_torrent_list() {
    local response=$(curl --silent --fail \
        ${CURL_OPT} \
        ${QBT_COOKIES} \
        --url "${QBITTORRENT}/api/v2/torrents/info?category=${CATEGORY_DL}" 2>/dev/null)
    local response_2=$(curl --silent --fail \
        ${CURL_OPT} \
        ${QBT_COOKIES} \
        --url "${QBITTORRENT}/api/v2/torrents/info?category=${CATEGORY_FZ}" 2>/dev/null)

    # Concatenate both lists : We want torrents from both categories.
    response=$(echo "$response" "$response_2" | jq -s 'add')

    if [[ $? -ne 0 || -z "$response" ]]; then
        log "ERROR: Failed to fetch full torrent list for category: $CATEGORY."
        return 1
    fi
    # log_debug "Full torrent list response: $response"

    # Use jq to transform the list into a dictionary mapping each hash to its torrent details
    response=$(echo "$response" | jq -c 'reduce .[] as $item ({}; .[$item.hash] = $item)')

    # log_debug "Full torrent list response reformatted: $response"
    
    echo "$response"
}

fetch_sync_data() {
    local rid=$1
    local nocache=$(date +%s%N)

    log_debug "Fetching /sync/maindata with RID: $rid"
    local response=$(curl --silent --fail \
        ${CURL_OPT} \
        ${QBT_COOKIES} \
        --url "${QBITTORRENT}/api/v2/sync/maindata?rid=${rid}&nocache=${nocache}" 2>/dev/null)

    if [[ $? -ne 0 || -z "$response" ]]; then
        log_error "Failed to fetch sync data from /sync/maindata."
        return 1
    fi

    log_debug "Sync data response: $response"
    echo "$response"
}

process_removed_torrents() {
    local sync_response=$1
    local combined_data=$2

    # Extract the list of removed torrents
    local torrents_removed=$(echo "$sync_response" | jq -c '.torrents_removed[]?')
    log_debug "Database: $combined_data"

    if [[ -n "$torrents_removed" ]]; then
        for torrent_hash in $torrents_removed; do
            # Strip quotes from the hash
            torrent_hash=$(echo "$torrent_hash" | tr -d '"')

            log_debug "Processing removed torrent: $torrent_hash"

            local torrent_data=$(echo "$combined_data" | jq --arg hash "$torrent_hash" '.torrents[$hash]')
            
            # Check if the torrent exists and is not null
            if [[ "$torrent_data" != "null" ]]; then
                local content_path=$(echo "$torrent_data" | jq -r '.content_path')
                log_debug "Content Path: $content_path"

                # Check if the path is a directory
                if [[ -d "$content_path" ]]; then
                    # Extract folder name
                    local folder_name=$(basename "$content_path")
                    local full_folder_path="$CATEGORY_DL_DIR/$folder_name"
                    
                    # Check if the folder exists
                    if [[ -d "$full_folder_path" ]]; then
                        log_debug "Folder exists: $full_folder_path"

                        # Remove .ftag files if present
                        local ftag_files=$(find "$full_folder_path" -type f -name "*.ftag")
                        if [[ -n "$ftag_files" ]]; then
                            log_debug "Removing .ftag files in $full_folder_path"
                            rm -f "$ftag_files" # Ensure quotes around $ftag_files to handle any spaces
                            # if the folder is now empty, remove it
                            if [[ -z "$(ls -A "$full_folder_path")" ]]; then
                                log_debug "Folder is now empty, removing: $full_folder_path"
                                rmdir "$full_folder_path"
                            fi
                        else
                            log_debug "No .ftag files found in $full_folder_path"
                        fi
                    else
                        log_debug "Folder does not exist: $full_folder_path"
                    fi
                else
                    log_debug "Content path is not a folder: $content_path"
                fi
            else
                log_debug "No matching torrent found for hash: $torrent_hash"
            fi
        done
    else
        log_debug "No removed torrents detected."
    fi
}



check_removed_torrents() {
    local prev_response=$1
    local rid=$(echo "$prev_response" | jq -r '.rid')
    local sync_response
    local new_rid
    local new_response

    # Fetch sync data
    sync_response=$(fetch_sync_data "$rid")

    # Parse new RID
    new_rid=$(echo "$sync_response" | jq -r '.rid')
    if [[ -z "$new_rid" ]]; then
        log_error "Failed to parse RID from response."
        return 1
    fi

    # Remove the .ftag for the removed torrents if applicable
    process_removed_torrents "$sync_response" "$prev_response"

    # Update response for next iteration
    new_response=$(fetch_full_torrent_list)
    new_response=$(update_combined_data "$new_response" "$new_rid")


    log_debug "Done processing sync data. Next try in $MAX_SLEEP_TIME seconds."
    echo $new_response
}

init_response() {
  if [[ -f "$RESPONSE_FILE" ]]; then
      response=$(cat "$RESPONSE_FILE")
      log_debug "Read RID from file."
  else
      log_debug "RID file not found, using default RID=0 with full torrent list fetch."
      response=$(fetch_full_torrent_list)
      response=$(update_combined_data "$response" "0")
  fi
  echo "$response"
}


init_checks


response=$(init_response)

while :; do
    response=$(check_removed_torrents "$response")
    # log_debug "Full response after check_removed_torrents: $response"
    sleep "${MAX_SLEEP_TIME}"
done
